"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "ar"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  // Load language preference from localStorage on client side
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "ar")) {
      setLanguage(savedLanguage)
      document.documentElement.dir = savedLanguage === "ar" ? "rtl" : "ltr"
      document.documentElement.lang = savedLanguage
    }
  }, [])

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr"
    document.documentElement.lang = language
  }, [language])

  // Simple translation function
  const t = (key: string): string => {
    return translations[language][key] || translations["en"][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    "app.name": "LaPure Medical Clinic",
    dashboard: "Dashboard",
    settings: "Settings",
    "new.case": "New Case",
    "new.simulation": "New Simulation",
    logout: "Logout",
    "save.changes": "Save Changes",
    saving: "Saving...",
    back: "Back",
    next: "Next",
    cancel: "Cancel",
    submit: "Submit",
    processing: "Processing...",

    // Dashboard
    "dashboard.title": "Dashboard",
    "total.cases": "Total Cases",
    "completed.simulations": "Completed Simulations",
    "pending.analysis": "Pending Analysis",
    "recent.cases": "Recent Cases",
    "completed.cases": "Completed Cases",
    "pending.cases": "Pending Cases",
    "search.cases": "Search cases...",

    // Settings
    "settings.title": "Settings",
    "settings.description": "Manage your account and clinic preferences",
    profile: "Profile",
    clinic: "Clinic",
    notifications: "Notifications",
    language: "Language",
    "language.english": "English",
    "language.arabic": "العربية",
    "full.name": "Full Name",
    email: "Email",
    phone: "Phone",
    "clinic.name": "Clinic Name",
    address: "Address",
    city: "City",
    state: "State",
    "zip.code": "Zip Code",
    "email.notifications": "Email Notifications",
    "email.notifications.description": "Receive notifications via email",
    "new.case.alerts": "New Case Alerts",
    "new.case.alerts.description": "Get notified when a new case is created",
    "weekly.reports": "Weekly Reports",
    "weekly.reports.description": "Receive weekly summary reports",
    "marketing.emails": "Marketing Emails",
    "marketing.emails.description": "Receive updates about new features and promotions",

    // New Case/Simulation
    "create.new.case": "Create New Case",
    "create.new.case.description": "Upload client images and select hairline options to begin the analysis",
    "create.new.simulation": "Create New Simulation",
    "create.new.simulation.description": "Upload a frontal image and select hairline options to visualize results",
    "client.information": "Client Information",
    "upload.images": "Upload Images",
    "upload.image": "Upload Image",
    "hairline.selection": "Hairline Selection",
    "client.name": "Client Name",
    age: "Age",
    notes: "Notes",
    "notes.placeholder": "Any additional information about the client...",
    "frontal.image": "Frontal Image for Simulation",
    "diagnostic.images": "Diagnostic Images (All Angles)",
    "front.view": "Front View",
    "left.side": "Left Side",
    "right.side": "Right Side",
    "back.view": "Back View",
    "select.hairline": "Select Hairline Shape",
    "recommended.hairstyles": "Recommended Hairstyles",
    "create.case": "Create Case & Continue to Analysis",
    "create.simulation": "Create Simulation",
    "drag.drop": "Drag & drop or click to upload",
    original: "Original",
    simulated: "Simulated",
    front: "Front",
    left: "Left",
    right: "Right",
    back: "Back",
    donor: "Donor",
    temporal: "Temporal",
    crown: "Crown",
    frontal: "Frontal",
    "high.density": "High Density",
    "medium.density": "Medium Density",
    "low.density": "Low Density",
    "health.score": "Health Score",
    "donor.strength": "Donor Strength",
    "estimated.grafts": "Estimated Grafts",
    "available.extraction": "Available for extraction",
    "suitable.transplant": "Suitable for transplant",
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    poor: "Poor",
    moderate: "Moderate",
    minimal: "Minimal",
    normal: "Normal",
    low: "Low",
    overview: "Overview",
    "donor.analysis": "Donor Analysis",
    "scalp.health": "Scalp Health",
    "diagnosis.summary": "Diagnosis Summary",
    "diagnosis.summary.p1":
      "Based on our AI analysis, the client has moderate hair loss (Norwood Scale 3-4) with good donor area potential. The scalp shows normal health with minimal signs of inflammation or scarring.",
    "diagnosis.summary.p2":
      "The client is a suitable candidate for hair transplantation with an estimated 2,800 grafts available from the donor area. The selected hairline shape (Arch) is appropriate for the client's facial structure and will provide natural-looking results.",
    "diagnosis.summary.p3":
      "We recommend proceeding with the graft planning phase to determine optimal distribution for natural-looking results.",
    "diagnosis.summary.short":
      "Client has moderate hair loss with good donor area potential. The scalp shows normal health with minimal signs of inflammation or scarring. Suitable candidate for hair transplantation.",
    "donor.area.analysis": "Donor Area Analysis",
    "donor.zone.visualization": "Donor Zone Visualization",
    "follicle.density.analysis": "Follicle Density Analysis",
    "occipital.region": "Occipital Region",
    "temporal.region": "Temporal Region",
    "parietal.region": "Parietal Region",
    "follicles.cm": "follicles/cm²",
    "follicle.type.distribution": "Follicle Type Distribution",
    "single.hair": "Single Hair",
    "double.hair": "Double Hair",
    "triple.hair": "Triple Hair",
    "scalp.health.assessment": "Scalp Health Assessment",
    "scalp.condition": "Scalp Condition",
    inflammation: "Inflammation",
    scarring: "Scarring",
    "sebum.production": "Sebum Production",
    "scalp.elasticity": "Scalp Elasticity",
    "microscopic.analysis": "Microscopic Analysis",
    recommendations: "Recommendations",
    "recommendation.1": "Use gentle, sulfate-free shampoo",
    "recommendation.2": "Apply minoxidil to improve blood flow",
    "recommendation.3": "Consider PRP therapy pre-transplant",
    "recommendation.4": "Maintain good scalp hygiene",
    "ai.analysis.progress": "AI Analysis in Progress",
    "ai.analysis.description":
      "Our AI is analyzing the uploaded images to assess scalp health, donor viability, and generate a comprehensive diagnosis. This may take a few moments.",
    "generating.graft.plan": "Generating Graft Plan",
    "graft.plan.description":
      "Our AI is calculating the optimal graft distribution based on the diagnosis results and selected hairline shape.",
    "heatmap.visualization": "Heatmap Visualization",
    "graft.distribution": "Graft Distribution",
    "graft.distribution.heatmap": "Graft Distribution Heatmap",
    "graft.distribution.summary": "Graft Distribution Summary",
    "frontal.area": "Frontal Area",
    "mid.scalp": "Mid-Scalp",
    crown: "Crown",
    grafts: "grafts",
    "recommendation.notes": "Recommendation Notes",
    "graft.recommendation.description":
      "The frontal area requires the highest density to create a natural-looking hairline. The mid-scalp needs moderate density to provide volume, while the crown area requires fewer grafts as it's less visible.",
    "total.grafts": "Total Grafts",
    "customize.graft.distribution": "Customize Graft Distribution",
    "adjust.distribution": "Adjust Distribution",
    "recommended.maximum": "Recommended maximum: 3,000 grafts based on donor availability.",
    "distribution.chart": "Distribution Chart",
    "export.options": "Export Options",
    "pdf.report": "PDF Report",
    print: "Print",
    share: "Share",
    "case.id": "Case ID",
    "created.on": "Created on",
    completed: "Completed",
    "in.progress": "In Progress",
    pending: "Pending",
    actions: "Actions",
    "view.diagnosis": "View Diagnosis",
    "view.graft.plan": "View Graft Plan",
    "export.report": "Export Report",
    "print.case": "Print Case",
    "share.with.client": "Share with Client",
    images: "Images",
    results: "Results",
    "client.images": "Client Images",
    "frontal.image.simulation": "Frontal Image (Simulation)",
    "analysis.results": "Analysis Results",
    "health.assessment": "Health Assessment",
    "overall.health.score": "Overall Health Score",
    "graft.plan": "Graft Plan",
    "view.full.plan": "View Full Plan",
    "view.detailed.plan": "View Detailed Plan",
    "select.hairline.first": "Please select a hairline shape first",
    "no.hairstyles": "No hairstyles available for this hairline type",
    "simulation.preview": "Simulation Preview",
    "hairline.type": "Hairline Type",
    "view.report": "View Consultation Report",
    "report.title": "Hair Transplant Consultation Report",
    "report.generated": "Report generated on",
    "assessment.tab": "Assessment",
    "characteristics.tab": "Characteristics",
    "recommendations.tab": "Recommendations",
    "hair.loss.assessment": "Hair Loss Assessment",
    "pattern.label": "Pattern",
    "severity.label": "Severity",
    "hairline.recession": "Hairline Recession",
    "crown.thinning": "Crown Thinning",
    "overall.density": "Overall Density",
    "distinctive.characteristics": "Distinctive Characteristics", 
    "hair.facial.characteristics": "Hair & Facial Characteristics",
    "hair.color": "Hair Color",
    "hair.texture": "Hair Texture",
    "hair.thickness": "Hair Thickness",
    "hair.density": "Hair Density",
    "face.shape": "Face Shape",
    "growth.pattern": "Growth Pattern",
    "treatment.recommendations": "Treatment Recommendations",
    "recommended.approach": "Recommended Approach",
    "estimated.graft.count": "Estimated Graft Count",
    "special.considerations": "Special Considerations",
    "expected.results": "Expected Results",
    "summary.title": "Summary",
    "consultation.disclaimer": "This report is generated based on AI analysis and is intended for consultation purposes only. Final treatment decisions should be made in consultation with a qualified hair transplant specialist.",
    "client.photo": "Client Photo",
    "analysis.recommendations": "Analysis & Recommendations",
    "print.button": "Print",
    "download.button": "Download",
    "share.button": "Share",
    "back.to.dashboard": "Back to Dashboard",
    "not.provided": "Not provided",
    "no.image": "No image available",
    "hairline": "Hairline",
    "hairstyle": "Hairstyle",
    "grafts": "grafts",
  },
  ar: {
    // General
    "app.name": "عيادة لابيور الطبية",
    dashboard: "لوحة التحكم",
    settings: "الإعدادات",
    "new.case": "حالة جديدة",
    "new.simulation": "محاكاة جديدة",
    logout: "تسجيل الخروج",
    "save.changes": "حفظ التغييرات",
    saving: "جاري الحفظ...",
    back: "رجوع",
    next: "التالي",
    cancel: "إلغاء",
    submit: "إرسال",
    processing: "جاري المعالجة...",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "total.cases": "إجمالي الحالات",
    "completed.simulations": "المحاكاة المكتملة",
    "pending.analysis": "التحليل المعلق",
    "recent.cases": "الحالات الأخيرة",
    "completed.cases": "الحالات المكتملة",
    "pending.cases": "الحالات المعلقة",
    "search.cases": "البحث في الحالات...",

    // Settings
    "settings.title": "الإعدادات",
    "settings.description": "إدارة حسابك وتفضيلات العيادة",
    profile: "الملف الشخصي",
    clinic: "العيادة",
    notifications: "الإشعارات",
    language: "اللغة",
    "language.english": "English",
    "language.arabic": "العربية",
    "full.name": "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    "clinic.name": "اسم العيادة",
    address: "العنوان",
    city: "المدينة",
    state: "الولاية",
    "zip.code": "الرمز البريدي",
    "email.notifications": "إشعارات البريد الإلكتروني",
    "email.notifications.description": "تلقي الإشعارات عبر البريد الإلكتروني",
    "new.case.alerts": "تنبيهات الحالات الجديدة",
    "new.case.alerts.description": "الحصول على إشعار عند إنشاء حالة جديدة",
    "weekly.reports": "التقارير الأسبوعية",
    "weekly.reports.description": "تلقي تقارير ملخصة أسبوعية",
    "marketing.emails": "رسائل التسويق",
    "marketing.emails.description": "تلقي تحديثات حول الميزات الجديدة والعروض الترويجية",

    // New Case/Simulation
    "create.new.case": "إنشاء حالة جديدة",
    "create.new.case.description": "قم بتحميل صور العميل واختيار خيارات خط الشعر لبدء التحليل",
    "create.new.simulation": "إنشاء محاكاة جديدة",
    "create.new.simulation.description": "قم بتحميل صورة أمامية واختيار خيارات خط الشعر لتصور النتائج",
    "client.information": "معلومات العميل",
    "upload.images": "تحميل الصور",
    "upload.image": "تحميل صورة",
    "hairline.selection": "اختيار خط الشعر",
    "client.name": "اسم العميل",
    age: "العمر",
    notes: "ملاحظات",
    "notes.placeholder": "أي معلومات إضافية عن العميل...",
    "frontal.image": "صورة أمامية للمحاكاة",
    "diagnostic.images": "صور تشخيصية (جميع الزوايا)",
    "front.view": "المنظر الأمامي",
    "left.side": "الجانب الأيسر",
    "right.side": "الجانب الأيمن",
    "back.view": "المنظر الخلفي",
    "select.hairline": "اختر شكل خط الشعر",
    "recommended.hairstyles": "تسريحات الشعر الموصى بها",
    "create.case": "إنشاء حالة ومتابعة التحليل",
    "create.simulation": "إنشاء محاكاة",
    "drag.drop": "اسحب وأفلت أو انقر للتحميل",
    original: "الأصلي",
    simulated: "المحاكاة",
    front: "أمامي",
    left: "يسار",
    right: "يمين",
    back: "خلفي",
    donor: "المانح",
    temporal: "صدغي",
    crown: "التاج",
    frontal: "أمامي",
    "high.density": "كثافة عالية",
    "medium.density": "كثافة متوسطة",
    "low.density": "كثافة منخفضة",
    "health.score": "درجة الصحة",
    "donor.strength": "قوة المنطقة المانحة",
    "estimated.grafts": "الطعوم المقدرة",
    "available.extraction": "متاح للاستخراج",
    "suitable.transplant": "مناسب للزراعة",
    excellent: "ممتاز",
    good: "جيد",
    fair: "مقبول",
    poor: "ضعيف",
    moderate: "متوسط",
    minimal: "الحد الأدنى",
    normal: "طبيعي",
    low: "منخفض",
    overview: "نظرة عامة",
    "donor.analysis": "تحليل المنطقة المانحة",
    "scalp.health": "صحة فروة الرأس",
    "diagnosis.summary": "ملخص التشخيص",
    "diagnosis.summary.p1":
      "بناءً على تحليل الذكاء الاصطناعي، يعاني العميل من تساقط شعر متوسط (مقياس نورود 3-4) مع إمكانية جيدة للمنطقة المانحة. تظهر فروة الرأس صحة طبيعية مع علامات طفيفة من الالتهاب أو الندبات.",
    "diagnosis.summary.p2":
      "العميل مرشح مناسب لزراعة الشعر مع تقدير 2800 طعم متاح من المنطقة المانحة. شكل خط الشعر المختار (قوس) مناسب لهيكل وجه العميل وسيوفر نتائج طبيعية المظهر.",
    "diagnosis.summary.p3":
      "نوصي بالمتابعة إلى مرحلة تخطيط الطعم لتحديد التوزيع الأمثل للحصول على نتائج طبيعية المظهر.",
    "diagnosis.summary.short":
      "العميل يعاني من تساقط شعر متوسط مع إمكانية جيدة للمنطقة المانحة. تظهر فروة الرأس صحة طبيعية مع علامات طفيفة من الالتهاب أو الندبات. مرشح مناسب لزراعة الشعر.",
    "donor.area.analysis": "تحليل المنطقة المانحة",
    "donor.zone.visualization": "تصور منطقة المانح",
    "follicle.density.analysis": "تحليل كثافة البصيلات",
    "occipital.region": "المنطقة القذالية",
    "temporal.region": "المنطقة الصدغية",
    "parietal.region": "المنطقة الجدارية",
    "follicles.cm": "بصيلة/سم²",
    "follicle.type.distribution": "توزيع نوع البصيلات",
    "single.hair": "شعرة واحدة",
    "double.hair": "شعرتان",
    "triple.hair": "ثلاث شعرات",
    "scalp.health.assessment": "تقييم صحة فروة الرأس",
    "scalp.condition": "حالة فروة الرأس",
    inflammation: "التهاب",
    scarring: "ندبات",
    "sebum.production": "إنتاج الزهم",
    "scalp.elasticity": "مرونة فروة الرأس",
    "microscopic.analysis": "التحليل المجهري",
    recommendations: "التوصيات",
    "recommendation.1": "استخدم شامبو لطيف خالي من الكبريتات",
    "recommendation.2": "ضع مينوكسيديل لتحسين تدفق الدم",
    "recommendation.3": "فكر في علاج البلازما الغنية بالصفائح الدموية قبل الزرع",
    "recommendation.4": "حافظ على نظافة فروة الرأس",
    "ai.analysis.progress": "تحليل الذكاء الاصطناعي قيد التقدم",
    "ai.analysis.description":
      "يقوم الذكاء الاصطناعي لدينا بتحليل الصور المحملة لتقييم صحة فروة الرأس، وقابلية المانح، وإنشاء تشخيص شامل. قد يستغرق هذا بضع لحظات.",
    "generating.graft.plan": "إنشاء خطة الطعم",
    "graft.plan.description":
      "يقوم الذكاء الاصطناعي لدينا بحساب التوزيع الأمثل للطعم بناءً على نتائج التشخيص وشكل خط الشعر المحدد.",
    "heatmap.visualization": "تصور خريطة الحرارة",
    "graft.distribution": "توزيع الطعم",
    "graft.distribution.heatmap": "خريطة حرارة توزيع الطعم",
    "graft.distribution.summary": "ملخص توزيع الطعم",
    "frontal.area": "المنطقة الأمامية",
    "mid.scalp": "وسط فروة الرأس",
    crown: "التاج",
    grafts: "طعوم",
    "recommendation.notes": "ملاحظات التوصية",
    "graft.recommendation.description":
      "تتطلب المنطقة الأمامية أعلى كثافة لإنشاء خط شعر طبيعي المظهر. يحتاج وسط فروة الرأس إلى كثافة معتدلة لتوفير الحجم، بينما تتطلب منطقة التاج طعومًا أقل لأنها أقل وضوحًا.",
    "total.grafts": "إجمالي الطعوم",
    "customize.graft.distribution": "تخصيص توزيع الطعم",
    "adjust.distribution": "ضبط التوزيع",
    "recommended.maximum": "الحد الأقصى الموصى به: 3000 طعم بناءً على توفر المانح.",
    "distribution.chart": "مخطط التوزيع",
    "export.options": "خيارات التصدير",
    "pdf.report": "تقرير PDF",
    print: "طباعة",
    share: "مشاركة",
    "case.id": "معرف الحالة",
    "created.on": "تم إنشاؤه في",
    completed: "مكتمل",
    "in.progress": "قيد التقدم",
    pending: "معلق",
    actions: "الإجراءات",
    "view.diagnosis": "عرض التشخيص",
    "view.graft.plan": "عرض خطة الطعم",
    "export.report": "تصدير التقرير",
    "print.case": "طباعة الحالة",
    "share.with.client": "مشاركة مع العميل",
    images: "الصور",
    results: "النتائج",
    "client.images": "صور العميل",
    "frontal.image.simulation": "الصورة الأمامية (المحاكاة)",
    "analysis.results": "نتائج التحليل",
    "health.assessment": "تقييم الصحة",
    "overall.health.score": "درجة الصحة الإجمالية",
    "graft.plan": "خطة الطعم",
    "view.full.plan": "عرض الخطة الكاملة",
    "view.detailed.plan": "عرض الخطة المفصلة",
    "select.hairline.first": "الرجاء تحديد شكل خط الشعر أولاً",
    "no.hairstyles": "لا توجد تسريحات شعر متاحة لهذا النوع من خط الشعر",
    "simulation.preview": "معاينة المحاكاة",
    "hairline.type": "نوع خط الشعر",
    "view.report": "عرض تقرير الاستشارة",
    "report.title": "تقرير استشارة الزرع الشعري",
    "report.generated": "تم إنشاء التقرير في",
    "assessment.tab": "التقييم",
    "characteristics.tab": "الخصائص",
    "recommendations.tab": "التوصيات",
    "hair.loss.assessment": "تقييم خسارة الشعر",
    "pattern.label": "النمط",
    "severity.label": "الشدة",
    "hairline.recession": "انتقال خط الشعر",
    "crown.thinning": "تصغير التاج",
    "overall.density": "كثافة عامة",
    "distinctive.characteristics": "الخصائص المميزة", 
    "hair.facial.characteristics": "الشعر والخصائص الوجدية",
    "hair.color": "لون الشعر",
    "hair.texture": "نوعية الشعر",
    "hair.thickness": "سمك الشعر",
    "hair.density": "كثافة الشعر",
    "face.shape": "شكل الوجه",
    "growth.pattern": "نمط النمو",
    "treatment.recommendations": "توصيات العلاج",
    "recommended.approach": "الطريقة الموصى بها",
    "estimated.graft.count": "عدد الطعوم المقدر",
    "special.considerations": "الملاحظات الخاصة",
    "expected.results": "النتائج المتوقعة",
    "summary.title": "الملخص",
    "consultation.disclaimer": "هذا التقرير موجه لأغراض الاستشارة فقط ويجب أن يتم اتخاذ القرارات العلاجية في إستشارة مع خبير زرع الشعر المؤهل.",
    "client.photo": "صورة العميل",
    "analysis.recommendations": "التحليل والتوصيات",
    "print.button": "طباعة",
    "download.button": "تحميل",
    "share.button": "مشاركة",
    "back.to.dashboard": "العودة للوحة التحكم",
    "not.provided": "لم تقدم",
    "no.image": "لا توجد صورة متاحة",
    "hairline": "خط الشعر",
    "hairstyle": "تسريحة الشعر",
    "grafts": "طعوم",
  },
}
